# Generated by Django 5.0.7 on 2024-08-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_visit_restaurant_remove_visit_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedrestaurant',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='visitedrestaurant',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookmarkedRestaurant',
        ),
        migrations.DeleteModel(
            name='VisitedRestaurant',
        ),
    ]
